package com.suprxsidh.stride.data.repository

import com.suprxsidh.stride.data.db.dao.ExerciseSessionDao
import com.suprxsidh.stride.data.db.dao.SyncStateDao
import com.suprxsidh.stride.data.db.dao.WeighInDao
import com.suprxsidh.stride.data.db.entity.ExerciseSessionEntity
import com.suprxsidh.stride.data.db.entity.SyncStateEntity
import com.suprxsidh.stride.data.db.entity.WeighInEntity
import com.suprxsidh.stride.health.HealthDataSource
import com.suprxsidh.stride.health.RemoteExerciseSession
import com.suprxsidh.stride.health.RemoteWeightRecord
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.time.Duration
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId

class HealthConnectRepositoryTest {

    /**
     * Honours the `since` bound the way Health Connect's own TimeRangeFilter does — a fake that
     * ignored it would make every "did the query window actually cover this record?" assertion
     * (the C1 shared-cursor and C2 publish-lag regressions) pass vacuously.
     */
    private class FakeDataSource(
        var sessions: List<RemoteExerciseSession> = emptyList(),
        var newWeights: List<RemoteWeightRecord> = emptyList()
    ) : HealthDataSource {
        val written = mutableListOf<Pair<Double, Instant>>()
        val sessionSince = mutableListOf<Instant>()
        val weightSince = mutableListOf<Instant>()

        override suspend fun readExerciseSessions(since: Instant): List<RemoteExerciseSession> {
            sessionSince.add(since)
            return sessions.filter { !it.startTime.isBefore(since) }
        }

        override suspend fun readNewWeightRecords(since: Instant): List<RemoteWeightRecord> {
            weightSince.add(since)
            return newWeights.filter { !it.time.isBefore(since) }
        }

        override suspend fun writeWeightRecord(weightKg: Double, time: Instant): String {
            written.add(weightKg to time)
            return "hc-written-${written.size}"
        }
    }

    private class FakeExerciseSessionDao : ExerciseSessionDao {
        val rows = mutableMapOf<String, ExerciseSessionEntity>()
        private val flow = MutableStateFlow<List<ExerciseSessionEntity>>(emptyList())
        override suspend fun getByHcRecordId(hcRecordId: String) = rows[hcRecordId]
        override suspend fun insert(session: ExerciseSessionEntity): Long {
            rows[session.hcRecordId] = session.copy(id = rows.size + 1L)
            flow.value = rows.values.sortedByDescending { it.startTimeEpochMs }
            return rows[session.hcRecordId]!!.id
        }
        override suspend fun update(session: ExerciseSessionEntity) {
            rows[session.hcRecordId] = session
            flow.value = rows.values.sortedByDescending { it.startTimeEpochMs }
        }
        override fun observeAll(): Flow<List<ExerciseSessionEntity>> = flow
        override suspend fun getLatestForDate(date: String) = rows.values.filter { it.date == date }.maxByOrNull { it.startTimeEpochMs }
    }

    private class FakeSyncStateDao : SyncStateDao {
        var state: SyncStateEntity? = null
        override suspend fun get() = state
        override suspend fun upsert(state: SyncStateEntity) { this.state = state }
    }

    private class FakeWeighInDao : WeighInDao {
        val rows = mutableListOf<WeighInEntity>()
        private var nextId = 1L
        private val flow = MutableStateFlow<List<WeighInEntity>>(emptyList())

        /**
         * Mirrors Room's `OnConflictStrategy.REPLACE` on `weigh_in`, whose only unique key is the
         * autogenerated primary key: an entity with `id == 0` ALWAYS becomes a brand-new row, even
         * when another row already holds the same date. (The previous fake silently deduped by date,
         * which hid the duplicate-per-date import bug entirely.)
         */
        override suspend fun upsert(weighIn: WeighInEntity): Long {
            val stored = if (weighIn.id != 0L) {
                rows.removeAll { it.id == weighIn.id }
                weighIn
            } else {
                weighIn.copy(id = nextId++)
            }
            rows.add(stored)
            flow.value = rows.toList()
            return stored.id
        }
        override fun observeAll(): Flow<List<WeighInEntity>> = flow
        override suspend fun getForDate(date: String) = rows.find { it.date == date }
        override suspend fun getByHcRecordId(hcRecordId: String) = rows.find { it.hcRecordId == hcRecordId }
        override suspend fun getUnsyncedToHc() = rows.filter { !it.syncedToHc }
    }

    private val fixedClock: () -> LocalDateTime = { LocalDateTime.of(2026, 8, 11, 10, 0) }

    /** The fixed clock as an Instant, so window assertions don't depend on the machine's zone. */
    private fun now(): Instant = fixedClock().atZone(ZoneId.systemDefault()).toInstant()

    private fun localInstant(y: Int, m: Int, d: Int, h: Int, min: Int): Instant =
        LocalDateTime.of(y, m, d, h, min).atZone(ZoneId.systemDefault()).toInstant()

    @Test
    fun `syncExerciseSessions inserts new sessions with computed analytics`() = runTest {
        val dataSource = FakeDataSource(
            sessions = listOf(
                RemoteExerciseSession(
                    hcRecordId = "hc-1",
                    exerciseType = "RUNNING",
                    startTime = Instant.parse("2026-08-11T06:00:00Z"),
                    endTime = Instant.parse("2026-08-11T06:32:00Z"),
                    distanceMeters = 5200.0,
                    kcalReal = 380,
                    heartRateSamplesBpm = listOf(140, 150, 160, 171)
                )
            )
        )
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)

        val count = repo.syncExerciseSessions()

        assertEquals(1, count)
        val stored = sessionDao.getByHcRecordId("hc-1")!!
        assertEquals(32, stored.durationMin)
        assertEquals(190, stored.kcalCredited) // 50% of 380, floored
        assertEquals(155, stored.avgHr)
        assertEquals(171, stored.maxHr)
    }

    @Test
    fun `syncExerciseSessions updates an existing session instead of duplicating`() = runTest {
        val dataSource = FakeDataSource(
            sessions = listOf(
                RemoteExerciseSession("hc-1", "RUNNING", Instant.parse("2026-08-11T06:00:00Z"), Instant.parse("2026-08-11T06:30:00Z"), 5000.0, 350, listOf(150))
            )
        )
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)
        repo.syncExerciseSessions()

        dataSource.sessions = listOf(
            RemoteExerciseSession("hc-1", "RUNNING", Instant.parse("2026-08-11T06:00:00Z"), Instant.parse("2026-08-11T06:35:00Z"), 5500.0, 400, listOf(155))
        )
        repo.syncExerciseSessions()

        assertEquals(1, sessionDao.rows.size)
        assertEquals(35, sessionDao.rows.getValue("hc-1").durationMin)
    }

    @Test
    fun `syncWeighIns pushes unsynced local entries to Health Connect`() = runTest {
        val weighInDao = FakeWeighInDao()
        weighInDao.upsert(WeighInEntity(date = "2026-08-10", weightKg = 80.0, syncedToHc = false))
        val dataSource = FakeDataSource()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), FakeSyncStateDao(), weighInDao, fixedClock)

        val count = repo.syncWeighIns()

        assertEquals(1, count)
        assertEquals(1, dataSource.written.size)
        assertTrue(weighInDao.rows.first().syncedToHc)
    }

    @Test
    fun `syncWeighIns imports a new Health Connect weight not seen before`() = runTest {
        val dataSource = FakeDataSource(
            newWeights = listOf(RemoteWeightRecord("hc-w-1", Instant.parse("2026-08-10T05:00:00Z"), 79.4))
        )
        val weighInDao = FakeWeighInDao()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), FakeSyncStateDao(), weighInDao, fixedClock)

        repo.syncWeighIns()

        val imported = weighInDao.getByHcRecordId("hc-w-1")
        assertEquals(79.4, imported!!.weightKg, 0.001)
        assertTrue(imported.syncedToHc)
    }

    @Test
    fun `syncWeighIns does not re-import an already-known Health Connect record`() = runTest {
        val weighInDao = FakeWeighInDao()
        weighInDao.upsert(WeighInEntity(date = "2026-08-10", weightKg = 79.4, syncedToHc = true, hcRecordId = "hc-w-1"))
        val dataSource = FakeDataSource(
            newWeights = listOf(RemoteWeightRecord("hc-w-1", Instant.parse("2026-08-10T05:00:00Z"), 79.4))
        )
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), FakeSyncStateDao(), weighInDao, fixedClock)

        repo.syncWeighIns()

        assertEquals(1, weighInDao.rows.size)
    }

    // --- C1: exercise sync must not consume the weigh-in cursor -----------------------------

    @Test
    fun `weigh-in import still works when exercise sync ran first in the same cycle`() = runTest {
        // The worker calls syncExerciseSessions() then syncWeighIns() against the SAME sync-state
        // row. With one shared cursor, the first call advanced the watermark to "now" and the second
        // then queried [now, now] — so no weigh-in was ever imported again after the first sync.
        val sharedSyncState = FakeSyncStateDao()
        val dataSource = FakeDataSource(
            sessions = listOf(runAt(localInstant(2026, 8, 11, 6, 0))),
            newWeights = listOf(RemoteWeightRecord("hc-w-1", now().minus(Duration.ofDays(1)), 79.4))
        )
        val weighInDao = FakeWeighInDao()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), sharedSyncState, weighInDao, fixedClock)

        repo.syncExerciseSessions()
        val imported = repo.syncWeighIns()

        assertEquals(1, imported)
        assertEquals(79.4, weighInDao.getByHcRecordId("hc-w-1")!!.weightKg, 0.001)
    }

    @Test
    fun `each half of sync advances only its own watermark`() = runTest {
        val sharedSyncState = FakeSyncStateDao()
        val repo = HealthConnectRepository(FakeDataSource(), FakeExerciseSessionDao(), sharedSyncState, FakeWeighInDao(), fixedClock)

        repo.syncExerciseSessions()
        assertEquals(now().toEpochMilli(), sharedSyncState.state!!.lastSyncEpochMs)
        assertNull(sharedSyncState.state!!.lastWeightSyncEpochMs)

        repo.syncWeighIns()
        assertEquals(now().toEpochMilli(), sharedSyncState.state!!.lastSyncEpochMs)
        assertEquals(now().toEpochMilli(), sharedSyncState.state!!.lastWeightSyncEpochMs)
    }

    @Test
    fun `repeated sync cycles keep importing new weigh-ins`() = runTest {
        val sharedSyncState = FakeSyncStateDao()
        val dataSource = FakeDataSource()
        val weighInDao = FakeWeighInDao()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), sharedSyncState, weighInDao, fixedClock)

        repo.syncExerciseSessions()
        repo.syncWeighIns()

        // A scale writes a weight a few hours later; the next cycle must still see it.
        dataSource.newWeights = listOf(RemoteWeightRecord("hc-w-2", now().minus(Duration.ofHours(2)), 78.9))
        repo.syncExerciseSessions()
        val imported = repo.syncWeighIns()

        assertEquals(1, imported)
        assertEquals(78.9, weighInDao.getByHcRecordId("hc-w-2")!!.weightKg, 0.001)
    }

    // --- C2: publish-lag lookback ------------------------------------------------------------

    @Test
    fun `a run published after the watermark was set is still picked up next cycle`() = runTest {
        // Samsung Health publishes a finished run into Health Connect 30-60 min late. With the
        // watermark as the exact left edge of the read window, such a run fell before every
        // subsequent window and was dropped permanently.
        val dataSource = FakeDataSource()
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)

        repo.syncExerciseSessions() // nothing available yet; watermark := now

        dataSource.sessions = listOf(runAt(now().minus(Duration.ofHours(2))))
        val count = repo.syncExerciseSessions()

        assertEquals(1, count)
        assertEquals(1, sessionDao.rows.size)
    }

    @Test
    fun `the read window is widened backwards but the stored watermark is not`() = runTest {
        val dataSource = FakeDataSource()
        val syncState = FakeSyncStateDao()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), syncState, FakeWeighInDao(), fixedClock)

        repo.syncExerciseSessions()
        repo.syncWeighIns()
        repo.syncExerciseSessions()
        repo.syncWeighIns()

        assertEquals(now().toEpochMilli(), syncState.state!!.lastSyncEpochMs)
        assertEquals(now().toEpochMilli(), syncState.state!!.lastWeightSyncEpochMs)
        assertTrue(dataSource.sessionSince.last().isBefore(now().minus(Duration.ofHours(24))))
        assertTrue(dataSource.weightSince.last().isBefore(now().minus(Duration.ofHours(24))))
    }

    @Test
    fun `a late-corrected run updates the existing row rather than duplicating it`() = runTest {
        val dataSource = FakeDataSource(sessions = listOf(runAt(now().minus(Duration.ofHours(4)), kcal = 350)))
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)
        repo.syncExerciseSessions()

        // Same record id re-read inside the lookback window, now with corrected calories.
        dataSource.sessions = listOf(runAt(now().minus(Duration.ofHours(4)), kcal = 420))
        repo.syncExerciseSessions()

        assertEquals(1, sessionDao.rows.size)
        assertEquals(420, sessionDao.rows.getValue("hc-late").kcalReal)
    }

    // --- I4: 3am logical day boundary --------------------------------------------------------

    @Test
    fun `a run started before 3am is stamped with the previous logical day`() = runTest {
        val dataSource = FakeDataSource(sessions = listOf(runAt(localInstant(2026, 8, 11, 1, 30))))
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)

        repo.syncExerciseSessions()

        assertEquals("2026-08-10", sessionDao.getByHcRecordId("hc-late")!!.date)
    }

    @Test
    fun `a run started after 3am keeps its own calendar day`() = runTest {
        val dataSource = FakeDataSource(sessions = listOf(runAt(localInstant(2026, 8, 11, 6, 15))))
        val sessionDao = FakeExerciseSessionDao()
        val repo = HealthConnectRepository(dataSource, sessionDao, FakeSyncStateDao(), FakeWeighInDao(), fixedClock)

        repo.syncExerciseSessions()

        assertEquals("2026-08-11", sessionDao.getByHcRecordId("hc-late")!!.date)
    }

    @Test
    fun `a weigh-in imported before 3am lands on the previous logical day`() = runTest {
        val dataSource = FakeDataSource(
            newWeights = listOf(RemoteWeightRecord("hc-w-1", localInstant(2026, 8, 11, 2, 0), 79.0))
        )
        val weighInDao = FakeWeighInDao()
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), FakeSyncStateDao(), weighInDao, fixedClock)

        repo.syncWeighIns()

        assertEquals("2026-08-10", weighInDao.getByHcRecordId("hc-w-1")!!.date)
    }

    // --- I5: never two rows for one logical day ----------------------------------------------

    @Test
    fun `importing a weight for a date that already has an entry updates it in place`() = runTest {
        val weighInDao = FakeWeighInDao()
        // Already synced, so the push loop leaves it alone; the incoming record is a *different*
        // Health Connect record (e.g. a smart scale) that happens to land on the same day.
        val existingId = weighInDao.upsert(
            WeighInEntity(date = "2026-08-11", weightKg = 80.0, syncedToHc = true, hcRecordId = "hc-mine")
        )
        val dataSource = FakeDataSource(
            newWeights = listOf(RemoteWeightRecord("hc-scale", localInstant(2026, 8, 11, 7, 0), 79.1))
        )
        val repo = HealthConnectRepository(dataSource, FakeExerciseSessionDao(), FakeSyncStateDao(), weighInDao, fixedClock)

        repo.syncWeighIns()

        assertEquals(1, weighInDao.rows.count { it.date == "2026-08-11" })
        val row = weighInDao.getForDate("2026-08-11")!!
        assertEquals(existingId, row.id)
        assertEquals(79.1, row.weightKg, 0.001)
        assertEquals("hc-scale", row.hcRecordId)
        assertTrue(row.syncedToHc)
    }

    private fun runAt(startTime: Instant, kcal: Int = 380) = RemoteExerciseSession(
        hcRecordId = "hc-late",
        exerciseType = "RUNNING",
        startTime = startTime,
        endTime = startTime.plus(Duration.ofMinutes(32)),
        distanceMeters = 5200.0,
        kcalReal = kcal,
        heartRateSamplesBpm = listOf(140, 150, 160, 171)
    )
}
