package com.suprxsidh.deficit.data.repository

import com.suprxsidh.deficit.data.calc.CalorieMath
import com.suprxsidh.deficit.data.calc.DayBoundary
import com.suprxsidh.deficit.data.calc.RunAnalytics
import com.suprxsidh.deficit.data.db.dao.ExerciseSessionDao
import com.suprxsidh.deficit.data.db.dao.SyncStateDao
import com.suprxsidh.deficit.data.db.dao.WeighInDao
import com.suprxsidh.deficit.data.db.entity.ExerciseSessionEntity
import com.suprxsidh.deficit.data.db.entity.WeighInEntity
import com.suprxsidh.deficit.health.HealthDataSource
import kotlinx.coroutines.flow.Flow
import java.time.Duration
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter

interface WeighInSyncSource {
    suspend fun syncWeighIns(): Int
}

class HealthConnectRepository(
    private val dataSource: HealthDataSource,
    private val exerciseSessionDao: ExerciseSessionDao,
    private val syncStateDao: SyncStateDao,
    private val weighInDao: WeighInDao,
    private val clock: () -> LocalDateTime = { LocalDateTime.now() }
) : WeighInSyncSource {
    private val dateFormatter = DateTimeFormatter.ISO_LOCAL_DATE

    fun observeExerciseSessions(): Flow<List<ExerciseSessionEntity>> = exerciseSessionDao.observeAll()

    suspend fun getLatestSessionForDate(date: String): ExerciseSessionEntity? =
        exerciseSessionDao.getLatestForDate(date)

    suspend fun syncExerciseSessions(): Int {
        val since = syncStateDao.get()?.lastSyncEpochMs?.let { Instant.ofEpochMilli(it) }
            ?: firstSyncFloor()
        // Watermark is captured BEFORE the read so anything published while this cycle runs is
        // still inside the next cycle's window.
        val watermark = clock().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()

        val remoteSessions = dataSource.readExerciseSessions(readSince(since))
        var count = 0
        for (remote in remoteSessions) {
            val durationMin = Duration.between(remote.startTime, remote.endTime).toMinutes().toInt()
            val avgPace = remote.distanceMeters?.let { RunAnalytics.avgPaceSecPerKm(durationMin, it) }
            val entity = ExerciseSessionEntity(
                hcRecordId = remote.hcRecordId,
                date = logicalDateOf(remote.startTime),
                exerciseType = remote.exerciseType,
                startTimeEpochMs = remote.startTime.toEpochMilli(),
                durationMin = durationMin,
                distanceM = remote.distanceMeters,
                avgPaceSecPerKm = avgPace,
                avgHr = RunAnalytics.avgHeartRate(remote.heartRateSamplesBpm),
                maxHr = RunAnalytics.maxHeartRate(remote.heartRateSamplesBpm),
                kcalReal = remote.kcalReal,
                kcalCredited = CalorieMath.creditedExerciseKcal(remote.kcalReal)
            )
            exerciseSessionDao.upsertByHcRecordId(entity)
            count++
        }

        syncStateDao.setExerciseSyncWatermark(watermark)
        return count
    }

    override suspend fun syncWeighIns(): Int {
        var count = 0
        for (unsynced in weighInDao.getUnsyncedToHc()) {
            val time = LocalDateTime.parse(unsynced.date + "T07:00:00").atZone(ZoneId.systemDefault()).toInstant()
            val hcId = dataSource.writeWeightRecord(unsynced.weightKg, time)
            weighInDao.upsert(unsynced.copy(syncedToHc = true, hcRecordId = hcId))
            count++
        }

        val since = syncStateDao.get()?.lastWeightSyncEpochMs?.let { Instant.ofEpochMilli(it) }
            ?: firstSyncFloor()
        val watermark = clock().atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()

        for (remote in dataSource.readNewWeightRecords(readSince(since))) {
            if (weighInDao.getByHcRecordId(remote.hcRecordId) != null) continue
            val date = logicalDateOf(remote.time)
            // A row may already exist for this logical day (manual entry, or a different provider's
            // record). weigh_in has no unique index on date, and upsert() REPLACEs on the
            // autogenerated primary key only, so inserting a fresh entity here would leave TWO rows
            // for one day and double-count it in the raw/rolling-average series. Update in place.
            val existing = weighInDao.getForDate(date)
            if (existing != null) {
                weighInDao.upsert(
                    existing.copy(weightKg = remote.weightKg, syncedToHc = true, hcRecordId = remote.hcRecordId)
                )
            } else {
                weighInDao.upsert(
                    WeighInEntity(date = date, weightKg = remote.weightKg, syncedToHc = true, hcRecordId = remote.hcRecordId)
                )
            }
            count++
        }

        syncStateDao.setWeightSyncWatermark(watermark)
        return count
    }

    private fun firstSyncFloor(): Instant =
        clock().minusDays(FIRST_SYNC_LOOKBACK_DAYS).atZone(ZoneId.systemDefault()).toInstant()

    /**
     * Widens the *read* window (never the stored watermark) backwards. Samsung Health publishes a
     * completed run into Health Connect 30-60 minutes after the fact, and other providers batch
     * even later — with the watermark as the exact left edge, anything published after the sync
     * that recorded it would fall before the next window and be dropped forever. Both entity types
     * are deduped on their Health Connect record id, so re-reading overlapping time is idempotent
     * and additionally picks up late calorie/heart-rate corrections.
     */
    private fun readSince(since: Instant): Instant = since.minus(SYNC_LOOKBACK)

    /**
     * Health Connect timestamps must go through the same 3am day boundary the rest of the app uses
     * (dashboard "today's run", weight logging), otherwise a run or weigh-in between midnight and
     * 3am is stamped with the next calendar day and never matches "today".
     */
    private fun logicalDateOf(instant: Instant): String =
        DayBoundary.logicalDate(instant.atZone(ZoneId.systemDefault()).toLocalDateTime()).format(dateFormatter)

    private companion object {
        val SYNC_LOOKBACK: Duration = Duration.ofHours(48)
        const val FIRST_SYNC_LOOKBACK_DAYS = 30L
    }
}
